# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#creating-a-workflow-file
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
name: Test Compilation Workflow

on:
  push:
    branches-exclude:
      - master
      - main

jobs:
  win64:
    timeout-minutes: 20
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # checkout the repository content to github runner.
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      #- name: Install correct version of configobj
        #run: python -m pip install 'git+git://github.com/DiffSK/configobj@3e2f4cca81b60171e6b3e23619f6f4929a13322e#egg=configobj'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pyinstaller
        run: |
          pip install pyinstaller
          pip install pyinstaller[encryption]
      - name: Install WX
        run: pip install wxPython
      - name: Tests
        # Make sure WX works, because pyinstaller doesn't complain if it's missing
        shell: python
        run: |
          import wx
          a = wx.App()
          w = wx.Frame(None, title='testing')
          del w
          del a
      - name: Compile
        shell: cmd
        run: pyinstaller --name="pyTestApp" main.pyw
      - name: Zip up locally
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'app.zip'
          directory: dist
          path: pyTestApp
      - name: Upload app archive
        uses: actions/upload-artifact@v3
        with:
          name: app.zip
          path: dist/app.zip
          retention-days: 1
      #- name: upload dist artifacts
        #uses: actions/upload-artifact@v3
        #with:
          #name: dist
          #path: dist
            #!dist/**/*.md
          #retention-days: 1
      #- name: Upload spec artifact
        #uses: actions/upload-artifact@v3
        #with:
          #name: main.spec
          #path: main.spec
          #retention-days: 1
