# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#creating-a-workflow-file
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
name: Test workflow

on:
  push:
    branches-exclude:
      - master
      - main

jobs:
  compile:
    timeout-minutes: 20
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # checkout the repository content to github runner.
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      #- name: Install correct version of configobj
        #run: python -m pip install 'git+git://github.com/DiffSK/configobj@3e2f4cca81b60171e6b3e23619f6f4929a13322e#egg=configobj'
      - name: Setup environment
        shell: python
        run: |
          import os
          print(f"Hello, you Git! The cwd is {os.getcwd()}.")
      #- name: upload artifacts
        #uses: actions/upload-artifact@v3
        #with:
          #name: dist-without-markdown
          #path: |
            #dist
            #!dist/**/*.md
      #- name: Archive code coverage results
        #uses: actions/upload-artifact@v3
        #with:
          #name: code-coverage-report
          #path: output/test/code-coverage.html
          #retention-days: 5
